FROM 47.97.167.185:9999/article-service/java:latest
MAINTAINER :2513120709@qq.com

COPY target/course-edge-service-1.0-SNAPSHOT.jar /course-edge-service.jar

ENTRYPOINT ["java" ,"-jar","/course-edge-service.jar"]