version: "3.4"
services:
  message-service:
    image: 47.97.167.185:9999/article-service/message-service:latest
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.2"
          memory: "128M"

  user-service:
    image: 47.97.167.185:9999/article-service/user-service:latest
    command:
      - "--mysql.address=121.40.8.72"
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"

  user-edge-service:
    image: 47.97.167.185:9999/article-service/user-edge-service:latest
    command:
      - "--redis.address=47.96.141.35"
    deploy:
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8082:8082"
    depends_on:
      - user-service
      - message-service

  course-service:
    image: 47.97.167.185:9999/article-service/course-service:latest
    command:
      - "--mysql.address=121.40.8.72"
      - "--zookeeper.address=47.96.141.35"
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    depends_on:
      - user-service

  course-edge-service:
    image: 47.97.167.185:9999/article-service/course-edge-service:latest
    command:
      - "--zookeeper.address=47.96.141.35"
    deploy:
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8081:8081"
    depends_on:
      - user-edge-service
  api-gateway:
    image: 47.97.167.185:9999/article-service/api-gateway-zuul:latest
    deploy:
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8087:80"
    depends_on:
      - user-edge-service
      - course-edge-service

networks:
  default:
    external:
      name: iooc-overlay
