FROM  47.97.167.185:9999/article-service/java:latest
MAINTAINER :2513120709@qq.com

COPY target/api-gateway-zuul-1.0-SNAPSHOT.jar /api-gateway-zuul.jar

ENTRYPOINT ["java" ,"-jar","/api-gateway-zuul.jar"]